version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: nextjs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: my_database       
      MYSQL_USER: user                  
      MYSQL_PASSWORD: password          
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


  # <div className="flex flex-col items-center justify-start gap-3 scroll-auto h-full w-1/3 bg-transparent  backdrop-blur-3xl  rounded-xl shadow-2xl">
  #       <div  ref={div1Ref}  className="overflow-y-auto w-full h-full [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] space-y-3 p-2">
  #           {user.map((user, index) => (
  #             <div
  #               key={index}
  #               className="flex flex-col items-center justify-center w-full h-1/3 bg-gray-500/30 rounded-lg shadow-2xl"
  #             >
  #               <h1 className="text-2xl font-bold text-white">{user.username}</h1>
  #               <p className="text-sm text-gray-300">{user.email}</p>
  #             </div>
  #           ))}
  #         </div>
  #     </div>
  #     <div className="flex flex-col items-center justify-start gap-3 scroll-auto h-full w-1/3 bg-transparent  backdrop-blur-3xl  rounded-xl shadow-2xl">
  #       <div ref={div2Ref}  data-index={5} className="overflow-y-auto w-full h-full [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] space-y-3 p-2">
  #           {user.map((user, index) => (
  #             <div
  #               key={index}
  #               className="flex flex-col items-center justify-center w-full h-1/3 bg-gray-500/30 rounded-lg shadow-2xl"
  #             >
  #               <h1 className="text-2xl font-bold text-white">{user.username}</h1>
  #               <p className="text-sm text-gray-300">{user.email}</p>
  #             </div>
  #           ))}
  #         </div>
  #     </div>
  #     <div className="flex flex-col items-center justify-start gap-3 scroll-auto h-full w-1/3 bg-transparent  backdrop-blur-3xl  rounded-xl shadow-2xl">
  #       <div  ref={div3Ref} className="overflow-y-auto w-full h-full [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none] space-y-3 p-2">
  #         {user.map((user, index) => (
  #           <div
  #             key={index}
  #             className="flex flex-col items-center justify-center w-full h-1/3 bg-gray-500/30 rounded-lg shadow-2xl"
  #           >
  #             <h1 className="text-2xl font-bold text-white">{user.username}</h1>
  #             <p className="text-sm text-gray-300">{user.email}</p>
  #           </div>
  #         ))}
  #       </div>
  #     </div>